sensor_kit_base_link:
  camera_front/camera_link:
    x: 0.5
    y: 0.0
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_back/camera_link:
    x: -0.5
    y: 0.0
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 3.14159265359
  camera_left/camera_link:
    x: 0.0
    y: 0.5
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 1.570796327
  camera_right/camera_link:
    x: 0.0
    y: -0.5
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: -1.570796327
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gnss_link:
    x: -0.1
    y: 0.0
    z: -0.2
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
