# Default configuration for spawn_vehicle.py
# This file defines the vehicle blueprint, role name, and sensor configuration

vehicle:
  # Vehicle blueprint ID (use --list-vehicles to see available options)
  blueprint: "vehicle.lincoln.mkz"
  
  # Role name for the vehicle (used to identify the vehicle in CARLA)
  role_name: "ego_vehicle"
  
  # Spawn point index (-1 for random)
  spawn_point: -1

sensors:
  # List of sensors to attach to the vehicle
  # Each sensor has: type, name, transform (location and rotation), and attributes
  
  - type: "sensor.lidar.ray_cast"
    name: "lidar_top"
    transform:
      location: [0.0, 0.0, 2.0]  # x, y, z in meters
      rotation: [0.0, 0.0, 0.0]  # pitch, yaw, roll in degrees
    attributes:
      channels: "32"
      range: "100.0"
      rotation_frequency: "10"
      points_per_second: "600000"
      upper_fov: "10.0"
      lower_fov: "-30.0"
  
  - type: "sensor.camera.rgb"
    name: "camera_front"
    transform:
      location: [1.5, 0.0, 1.5]
      rotation: [0.0, 0.0, 0.0]
    attributes:
      image_size_x: "1920"
      image_size_y: "1080"
      fov: "90"
  
  - type: "sensor.camera.rgb"
    name: "camera_rear"
    transform:
      location: [-1.5, 0.0, 1.5]
      rotation: [0.0, 180.0, 0.0]
    attributes:
      image_size_x: "1280"
      image_size_y: "720"
      fov: "110"
  
  - type: "sensor.other.imu"
    name: "imu"
    transform:
      location: [0.0, 0.0, 0.0]
      rotation: [0.0, 0.0, 0.0]
    attributes: {}
  
  - type: "sensor.other.gnss"
    name: "gnss"
    transform:
      location: [-1.0, 0.0, 1.0]
      rotation: [0.0, 0.0, 0.0]
    attributes: {}
  
  - type: "sensor.other.radar"
    name: "radar_front"
    transform:
      location: [2.0, 0.0, 1.0]
      rotation: [0.0, 0.0, 0.0]
    attributes:
      horizontal_fov: "30"
      vertical_fov: "10"
      range: "100"

# Simulation settings
simulation:
  # Whether to run in synchronous mode
  sync_mode: false
  
  # Fixed time step for synchronous mode (seconds)
  fixed_delta_seconds: 0.05
